config/routes.rb
# See how all your routes lay out with "rake routes"
Fontli::Application.routes.draw do
  # Api controller
  match '/api/:action(.:format)', :controller => 'api_actions'

  # new web routes
  match 'feeds' => 'feeds#index', :as => :feeds
  match 'feeds/show/:id' => 'feeds#show', :as => :show_feed
  match 'socialize-feed/:id' => 'feeds#socialize_feed', :as => :socialize_feed
  match 'follow-user/:id' => 'feeds#follow_user', :as => :follow_user
  match 'unfollow-user/:id' => 'feeds#unfollow_user', :as => :unfollow_user
  match 'sos' => 'feeds#sos', :as => :sos
  match 'feed/:id/fonts' => 'feeds#fonts', :as => :feed_fonts
  match 'fonts/:family_id/:font_id' => 'feeds#show_font', :as => :show_font
  match 'recent-fonts' => 'feeds#recent_fonts', :as => :recent_fonts
  match 'profile/:user_id' => 'feeds#profile', :as => :profile
  match 'popular' => 'feeds#popular', :as => :popular
  match 'my-updates' => 'feeds#my_updates', :as => :my_updates
  match 'network-updates' => 'feeds#network_updates', :as => :network_updates
  match 'search-autocomplete' => 'feeds#search_autocomplete', :as => :search_autocomplete
  match 'search' => 'feeds#search', :as => :search
  match "font-autocomplete" => "fonts#font_autocomplete", :as => :font_autocomplete
  match "font-details/:fontname" => "fonts#font_details", :as => :font_details
  match "sub-font-details/:uniqueid" => "fonts#sub_font_details", :as => :sub_font_details
  match 'tag_font' => 'fonts#tag_font', :as => :tag_font

  # Old Unused routes
  match 'post-feed' => 'feeds#post_feed', :as => :post_feed
  match 'publish-feed/:id' => 'feeds#publish_feed', :as => :publish_feed
  match 'detail_view' => 'feeds#detail_view', :as => :detail_view
  match 'get_mentions_list' => 'feeds#get_mentions_list', :as => :get_mentions_list

  # welcome controller
  root :to => 'welcome#index'

  match 'keepalive' => 'welcome#keepalive', :as => :keepalive
  match 'signup/:platform' => 'welcome#signup', :as => :signup
  match 'login/:platform'  => 'welcome#login',  :as => :login
  match 'auth/:platform/callback' => 'welcome#auth_callback', :as => :auth_callback
  match 'logout' => 'welcome#logout', :as => :logout

  # admin controller
  match 'admin' => 'admin#index', :as => :admin
  match 'admin/:action', :controller => 'admin'

  # Resque Web
  mount Resque::Server.new, :at => "/resque"

  # Utils
  constraints :host => /(localhost|staging\.fontli\.com)/i do
    match 'doc' => 'welcome#api_doc'
  end

  # Permalink - Has to be the last one
  match '*url' => 'feeds#permalink'
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  #skip_before_filter :login_required, :only => [:show, :fonts, :permalink]
  skip_before_filter :login_required, :only => [:show, :fonts, :permalink, :profile, :popular, :search, :recent_fonts, :search_autocomplete, :show_font]

  def index
    @photos = Photo.feeds_for(current_user, (params[:page] || 1)).to_a
    preload_photos_my_likes_comments
  end

  def show
    @photo = Photo.find(params[:id])
    preload_photo_associations
    render 'show', :layout => false
  end

  def permalink
    url = Base64.urlsafe_decode64(URI.unescape(params[:url]))
    klass, id = url.split('_')
    @photo, @perma = klass.constantize.find(id.to_s), true
    preload_photo_associations
    @meta_title = 'Photo Detail'
    render 'show', :layout => 'plain'
  rescue
    render :file => 'public/404.html', :status => '404', :layout => false
  end

  def sos
    @photos = Photo.sos(params[:page] || 1).to_a
    preload_photos_my_likes_comments
  end

  def fonts
    @fonts = Photo[params[:id]].fonts.desc(:created_at).to_a
    render :partial => 'spotted_pop', :layout => false
  end

  def recent_fonts
    @fonts = Font.popular.to_a
  end

  def show_font
    @font = Font[params[:font_id]]
    # @details = Rails.cache.fetch("font_family_details_#{params[:family_id]}") do
    #  FontFamily.family_details(params[:family_id])
    # end

    case params[:type]
    when 'fav'
      @users = @font.fav_users(params[:page], 18).to_a
    else
      opts = { :family_id => params[:family_id], :page => params[:page] }
      @photos = Font.tagged_photos_for(opts, 18).to_a
      preload_photos_my_likes_comments
    end
    @meta_title = 'Font Detail'
  end

  def profile
    params[:username] = nil if params[:username] == 'You'
    @user = if !params[:user_id].blank?
              User.by_id(params[:user_id])
            elsif !params[:username].blank?
              User[params[:username]]
            else
              current_user
            end
    page = params[:page] || 1
    offst = (page.to_i - 1) * 18

    case params[:type]
    when 'like'
      @photos = @user.fav_photos(page, 18).to_a
      preload_photos_my_likes_comments(:skip_likes => true)
    when 'fav_font'
      @fonts = @user.my_fav_fonts(page, 18).to_a
      #preload_fonts_photos # this is more tricky
    when 'spotted'
      @photos = @user.spotted_photos(page, 18).to_a
      preload_photos_my_likes_comments
    when 'followers'
      @users = @user.followers.limit(18).skip(offst).to_a
    when 'follows'
      @users = @user.friends.limit(18).skip(offst).to_a
    else
      @photos = @user.photos.recent(18).skip(offst).to_a
      preload_photos_my_likes_comments
    end
  end

  def popular
    case params[:type]
    when 'post'
      @photos = Photo.popular
      preload_photos_my_likes_comments
    when 'font'
      @fonts = Font.api_recent
    else
      @users = User.recommended
    end
  end

  def post_feed
    return if request.get?
    @photo = current_user.photos.unpublished.first
    @photo ||= current_user.photos.new(:caption => Photo::DEFAULT_TITLE)
    @photo.data = params[:photo]
    @status = @photo.save
    redirect_to :action => "index", :photo_id => @photo.id
  end

  def publish_feed
    return if request.get?
    @photo = current_user.photos.unpublished.find(params[:id])
    @photo.caption = params[:caption]
    @photo.crop = params[:crop]
    @photo.created_at = Time.now.utc
    if @photo.save
    redirect_to feeds_url, :notice => "Posted to feed, successfully."
    end
  end
  
  def remove_unpublished_feed
    @photo = current_user.photos.unpublished.find(params[:photo_id])
    @photo.destroy
  end

  def socialize_feed
    @photo = Photo.find(params[:id])
    meth_name = "#{params[:modal]}_feed".to_sym
    self.method(meth_name).call
    @photo.reload # to read the new likes_count/comments_count
    render meth_name
  end

  def follow_user
    @user = User.find(params[:id])
    current_user.follows.new(:follower_id => @user.id).save
  end

  def unfollow_user
    @user = User.find(params[:id])
    current_user.follows.where(:follower_id => @user.id).first.destroy
    render 'follow_user'
  end

  def detail_view
    @foto = Photo.find(params[:id])
  end
  
  def get_mentions_list
    @foto = Photo.find(params[:id])
    @mentions_list = current_user.mentions_list(@foto.id)
  end

  def search_autocomplete
    term, lmt = params[:term], 7
    users = User.search_autocomplete(term, lmt)
    posts = Photo.search_autocomplete(term, lmt)
    fonts = Font.search_autocomplete(term, lmt)

    # users and fonts takes precedence over posts
    results = (users + fonts + posts).uniq.first(lmt)
    render :json => results.sort_by(&:length)
  end

  def search
    term = params[:search]
    @users = User.search(term)
    @posts = Photo.search(term)
    # Return only uniq fonts by family_id/subfont_id
    @fonts = Font.search(term).uniq(&:key)
  end

  private

  def like_feed
    lke = @photo.likes.new(:user_id => current_user.id)
    lke.save
  end

  def unlike_feed
    lke = @photo.likes.where(:user_id => current_user.id).first
    lke.destroy
  end

  def comment_feed
    @cmt = @photo.comments.new(
      :user_id => current_user.id,
      :body => params[:comment]
    )
    @status = @cmt.save
  end

  def share_feed
  end

  def flag_feed
    flg = @photo.flags.new(:user_id => current_user.id)
    flg.save
  end

  def unflag_feed
    flg = @photo.flags.where(:user_id => current_user.id).first
    flg.destroy
  end

  def remove_feed
    @status = @photo.destroy
  end

  # loads all likes and comments with associated users for a foto.
  def preload_photo_associations(foto = nil)
    foto ||= @photo
    @likes = foto.likes.desc(:created_at).to_a
    lkd_usr_ids = @likes.collect(&:user_id)
    @comments = foto.comments.desc(:created_at).to_a
    cmt_usr_ids = @comments.collect(&:user_id)
    
    unless (lkd_usr_ids + cmt_usr_ids).empty?
      usrs = User.where(:_id.in => (lkd_usr_ids + cmt_usr_ids)).only(:id, :username, :avatar_filename).to_a
      @users_map = usrs.group_by(&:id)
    end
  end

  def preload_photos_my_likes_comments(opts={})
    f_ids, user = @photos.collect(&:id), @user
    if f_ids.any?
      @users_map = User.where(:_id.in => @photos.collect(&:user_id)).group_by(&:id)
      @my_lks = @my_cmts = {}
      return true

      unless opts[:skip_likes]
        @my_lks = user.likes.where(:photo_id.in => f_ids).desc(:created_at).group_by(&:photo_id)
      end
      @my_cmts = user.comments.where(:photo_id.in => f_ids).desc(:created_at).group_by(&:photo_id)
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper

  def cta_button(id, val, lbl)
    content_tag(
      :button, lbl, :type => 'submit', 
      :id => (val + '_' + id), :value => val, :name => 'modal'
    )
  end
  
  def foto_classes(index)
    position = index.even? ? "float_left" : "float_right"
    rotate_count = (index % 4) + 1
    "column " + position + " rotate_" + rotate_count.to_s
  end
end

app/views/feeds/_comments_content.html.erb
<% comments = foto.comments%>
<div id="font_comment" class="slide">
  <h1>Comments</h1>
  <% unless comments.blank? %>
  <% comments.each do |comment| %>
  <div class="comment_listing clear">
    <%= image_tag(comment.user.url_thumb, :class=>"rounded_corner float_left")%>
    <div class="comment_description">
      <h5><a href="#"><%= comment.username%></a></h5>
      <p>
        <%= comment.body%>
      </p>
      <p class="small_text">
        <%= timestamp(comment.created_at) %>
      </p>
    </div>
  </div>
  <%end%>
  <% end %>
</div>
<%= render "new_comment", :foto => foto%> 

app/views/feeds/_detail_view_fonts.html.erb
<div id="font_spotted" class="slide">
  <h1>FONTS</h1>
  <% foto.fonts.each do |font|%>
  <div class="fonts clear">
    <div class="font_names">
      <% href,image = buy_at_href(font.family_id)%> <h4><a href="#"><%= font.subfont_name ? font.subfont_name : font.family_name %></a></h4>
      <h2 class="font_sample"><%= image.html_safe%></h2>
    </div>
    <div class="font_tags">
      <a class="spot_on rounded_corner" href="#">Spot on</a>
      <p class="small_text third_color uppercase">
        30 Tags , 12 Agrees
      </p>
    </div>
    <div class="buy_at">
      <p class="uppercase">
        Buy at
      </p>
      <%= link_to(image_tag("support_logo.png"),{},{:href => href})%>
    </div>
  </div>
  <%end%>
</div>

app/views/feeds/_detail_view_header.html.erb
<div class="meta_elements">
  <h5 class="photo_title"><%= foto.caption%></h5>
  <ul class="photo_meta">
    <li>
      <%= link_to foto.fonts.count, {}, {:href => "#", :class => "font_types"}%>
    </li>
    <li>
      <%= link_to foto.comments.count, {}, {:href => "#", :class => "comments"}%>
    </li>
    <li>
      <%= link_to foto.likes.count, {}, {:href => "#", :class => "liked"}%>
    </li>
  </ul>
</div>

app/views/feeds/_spot_list.html.erb
<div class="comment-box clr">
  <% @fonts.each do |f| %>
    <div class="set3c">
      <img src="<%= f[:image] %>" width="300" alt="">
      <span class='font-name'><%= f[:name] %></span>
      <div class="spotted" data-id="<%= f[:uniqueid] %>">
        <button class="small-btn-spotted spot-this">Spot</button>
        <button class="small-btn-black view-family">View Family (<%= f[:count] %>)</button>
      </div>
      <%= form_tag tag_font_path, :id => "tag_form_#{f[:uniqueid]}", :remote => true do %>
        <%= hidden_field_tag :photo_id, '', :class => 'photo-id-input' %>
        <%= hidden_field :font, :family_unique_id, :value => f[:uniqueid] %>
        <%= hidden_field :font, :family_name, :value => f[:name] %>
        <%= hidden_field :font, :family_id, :value => f[:id] %>
        <%= hidden_field :font, :img_url, :value => f[:image] %>
        <%= hidden_field :font, :coords, :class => 'coords-input' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/feeds/follow_user.js.erb
// update the button
var elem = $('#follow_btn_<%= params[:id] %>');
elem.replaceWith("<%= escape_javascript(render_follow_button(@user)) %>");
hideAjaxLoader();

app/views/feeds/like_feed.js.erb
// update the likes count
$('#likes_cnt_<%= params[:id] %>').html("<%= pluralize(@photo.likes_count, 'like') %>");
$('#likes_cnt_<%= params[:id] %>').removeClass('hidden');
// update the button
var elem = $('#like_<%= params[:id] %>');
elem.replaceWith("<%= escape_javascript(render_photo_like_button(@photo, true)) %>");
hideAjaxLoader();

app/views/feeds/popular.html.erb
<section id="stream">
<div class="pro-header-a">
  <section class="popular-section">
  <% if params[:type] == 'post' %>
    <span>Popular</span>
  <% elsif params[:type] == 'font' %>
    <span>Recently Spotted</span>
  <% else %>
    <span>Limelight</span>
  <% end %>
  </section>
</div>

<% if false %>
<div class="nav">
  <section>
  <div class="pro-header-c">
    <%= render 'popular_cta' %>
  </div>
  </section>
</div>
<% end %>

<section id='popular_section_container'>
  <% if params[:type] == 'post' %>
    <%= render '/shared/photo_list' %>
  <% elsif params[:type] == 'font' %>
    <%= render '/shared/font_list' %>
  <% else %>
    <%= render '/shared/account_list' %>
  <% end %>
</section>
</section>

app/views/feeds/popular.js.erb
<% contents = if params[:type] == 'font' %>
  <% render '/shared/font_list' %>
<% elsif params[:type] == 'post' %>
  <% render '/shared/photo_list' %>
<% else %>
  <% render '/shared/account_list' %>
<% end %>
<% if params[:type].blank? # accounts %>
  $('#stream').attr('id', 'stream-2');
<% else # posts/fonts %>
  $('#stream-2').attr('id', 'stream');
<% end %>
$('#popular_section_container').html('<%= escape_javascript(contents) %>');
$('.popular-cta').removeClass('selected');
<% typ = params[:type] || 'account' %>
$(".popular-cta.<%= typ %>").addClass('selected');
hideAjaxLoader();

app/views/feeds/post_feed.html.erb
<% if @status %>
  <%= render "publish_foto_form", :foto => @photo %>
<% else %>
  <%= render "upload_foto_form", :errors => @photo.errors.full_messages %>
  <%= link_to 'Back', feeds_path %>
<%  end %>

app/views/feeds/publish_feed.html.erb
<%= render "publish_foto_form", :foto => @photo %>

app/views/feeds/show.html.erb
<% user = @photo.user %>
<% likes_cnt, comments_cnt, fonts_cnt = @photo.likes_count, @photo.comments_count, @photo.fonts_count %>
<% fnts_map = fonts_map_for_comments @comments %>

<div class="popup <%= @open_popup ? 'open' : 'closed' %>">
  <div class="left-pop">
    <div class="bigpic" data-id="<%= @photo.id.to_s %>">
      <div class="img-overlay"></div>
      <img src="<%= @photo.url(:large) %>" style="width:480px;height:480px;"/>
      <a href="javascript:;" data-href='<%= show_feed_path(0) %>' class="set4"></a>
      <a href="javascript:;" data-href='<%= show_feed_path(0) %>' class="set5"></a>

      <div id='tag_locator' class='hidden'>
        <img src='<%= asset_path('taglabelmark.png') %>' id="tag_labelmark" class="draggable" />
        <p>Place this marker on the image where the font is spotted</p>
      </div>
    </div>
    <div class="hidden" id="permalink_url" data='<%= @photo.permalink %>'></div>

    <ul class="set1 icons">
      <% (['a', 'b', 'c']).each do |char| %>
      <li class="set1-<%= char %> <%= 'login-req' unless logged_in? %>">
        <i></i>
        <div class="hover"></div>
      </li>
      <% end %>
    </ul>
    <ul class="set1">
      <li class='set1-cross'>
        <a href='javascript:;' class='cross'></a>
      </li>
    </ul>

    <ul class="set3">
      <li class="profile-name">
        <a href="<%= profile_path(:user_id => user.id) %>">
          <span><%= user.username %></span>
        </a>
      </li>
      <li class="profile-dialog">
        <span><%= truncate(@photo.caption, :length => 100) %></span>
      </li>
      <li class="profile-detail">
        <%= photo_details_li %>
      </li>
    </ul>
    <% if @photo.fonts_count > 0 %>
    <% fnt = @photo.fonts.desc(:agrees_count).first %>
    <div class="set3b">
      <a href="<%= show_font_path(fnt.family_id, :font_id => fnt.id) %>">
        <img src='<%= fnt.img_url %>' width="350px" />
        <span class='pop-disclaimer'>
          <%= fnt.display_name %>
          <%= pluralize(fnt.agrees_count, 'Agree') %>
          <img src="<%= asset_path('Agreed--Default.png') %>" width="22" height="18" title="Agree" />
        </span>
      </a>
    </div>
    <% end %>
  </div>

  <div class="right-pop">
    <header>
      <span class='header-title'>Typetalk</span>
      <a href="javascript:;" class="collapse flt-left"></a>
      <a href="javascript:;" class="cross flt-right"></a>
      <!--  <a href="javascript:;" class="settings flt-right"></a> -->
    </header>
    <div class="content-a">
      <a class="propic" href="<%= profile_path(:user_id => user.id) %>">
        <img src="<%= user.url(:thumb) %>" width="100%" height="100%">
        <div class="overlap"></div>
      </a>
      <ul>
        <li class="a">
          <a href="<%= profile_path(:user_id => user.id) %>">
            <span class="name"><%= user.username %></span>
          </a>
          <span class="time"><%= timestamp(@photo.created_at) %></span>
        </li>
        <li class="b">
          <span><%= @photo.caption %></span>
        </li>
        <li class="c">
          <style type="text/css">
            .twitter-share-button { width:60px !important }
          </style>
          <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= @photo.permalink %>" data-text="@fontli, Fontli- discover and share pure type love!" data-count="none"></a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
          <a href="javascript:;" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<%= CGI.escape(@photo.permalink) %>','facebook-share-dialog','width=626,height=436'); return false;" style="height:24px;width:64px;vertical-align:bottom;display:inline-block;"><img src="<%= asset_path('fb_share_button.png') %>" /></a>
        </li>
      </ul>
    </div>
    <div class="like-box pop-nav">
      <a class='view-likes' href="javascript:;">
        <%= pluralize(likes_cnt, 'like') %>
      </a>
      <a class='view-typetalk' href="javascript:;">
        <%= pluralize(comments_cnt, 'comment') %>
      </a>
      <a class='view-spotted' data-url='<%= feed_fonts_path(:id => @photo.id) %>' href="javascript:;">
        <%= pluralize(fonts_cnt, 'spotting') %>
      </a>
      <a href="javascript:;" class="like <%= 'login-req' unless logged_in? %>">
        <img src="<%= asset_path('heartsmall.png') %>" />
      </a>
      <a href="javascript:;" class="like spot <%= 'login-req' unless logged_in? %>">
        <img src="<%= asset_path('Spot-Selected.png') %>" />
      </a>
    </div>
    <div style="clear:both;"></div>

    <div class="like-box spot-search hidden">
      <input type="text" name="spot-search" placeholder="search..."  style="color:#666" />
    </div>
    <div class="like-box spot-preview hidden">
      <input type="text" class='search-input-bottom' name='spot-preview' placeholder="Type preview text..."  style="color:#666" />
    </div>
    <div class="aa-spotted content content-b" style="display:none;"></div>
    <div class="aa-spot-list content content-b" style="display:none;"></div>
    <div class="aa-spot-list-family content content-b" style="display:none;"></div>
    <div class="aa-likes content content-b" style="display:none;">
      <%= render 'liked_pop' %>
    </div>
    <div class="aa-typetalk content content-b" style='margin-bottom:50px;'>
      <div class="comment-box clr">
        <% if likes_cnt > 0 %>
        <div class="recent-likes">
          <% recent_likes = @likes[0..4] %>
          <% recent_likes.each do |l| %>
            <% u = @users_map[l.user_id].first %>
            <a href="<%= profile_path(:user_id => u.id) %>" class="propic">
              <img src="<%= u.url_thumb %>" width="100%" height="auto" />
              <div class="overlap"></div>
            </a>
          <% end %>
          <a href="javascript:;" class="view-likes">
            <% if likes_cnt > 0 && likes_cnt <= recent_likes.length %>
              <br/><%= pluralize(likes_cnt, 'like') %>
            <% end %>
            <% if likes_cnt > recent_likes.length %>
              <br/>+<%= pluralize(likes_cnt - recent_likes.length, 'like') %>
            <% end %>
          </a>
          <div style='clear:left;'></div>
        </div>
        <% end %>

        <% @comments.each do |c| %>
          <% u = @users_map[c.user_id].first %>
          <%= render 'shared/comment_content', :c => c, :u => u, :fnts_map => fnts_map %>
        <% end %>
      </div>
    </div>
    <div class="bottom-nav <%= 'hidden' unless logged_in? %>">
      <form action="<%= socialize_feed_path(@photo.id, :modal => 'comment') %>" class='comment-form'>
        <input type="text" name="comment" placeholder="Your Comment..." autocomplete='off' />
      </form>
    </div>
  </div>
</div>

app/views/feeds/show_font.html.erb
<% content_for :custom_js do %>
  <%= render 'shared/pinned_header_js' %>
<% end %>

<section id="stream">
<div class="font-details">
  <div class="wrapper">
    <div class="left-panel">
      <span><%= @font.owner %></span>
      <h1><%= @font.display_name %></h1>
      <p><%= @font.desc %></p>
      <a href="<%= @font.myfonts_url || "#" %>" class="font-desc-view-more" target="blank">View more</a>
    </div>
    <div class='right-panel'>
      <img src="<%= @font.image %>" width="290" height="auto" />
      <span><%= @font.display_name %></span>
    </div>
  </div>
</div>
<div class="pro-header-d" id='pinned_header'>
  <div class="wrapper">
    <ul class="float-Lt">
      <li class="font-detail-cta post <%= 'selected' if params[:type].nil? %>">
        <a data-href="<%= show_font_path(@font.family_id, :font_id => @font.id) %>" remote=true><%= @font.tagged_photos_count %> Post</a>
      </li>
      <li class="font-detail-cta fav <%= 'selected' if params[:type] == 'fav' %>">
        <a data-href="<%= show_font_path(@font.family_id, :font_id => @font.id, :type => 'fav') %>" remote=true><%= @font.favs_count %> Favourite</a>
      </li>
    </ul>
    <div class="float-Rt">
      <a href="<%= @font.myfonts_url || "#" %>" target="_blank">
        <span>Buy at</span>
        <img src="<%= asset_path('myfont.png') %>" width="76" height="39" alt="My Fonts" title="My Fonts" />
      </a>
    </div>
  </div>
</div>
<section id="font_section_container">
  <%= render '/shared/photo_list' %>
</section>
<div class="loader hidden" style="width:32px;margin:10px auto;">
  <img src='<%= asset_path('ajax-loader-sm.gif') %>' alt='Loading...' />
</div>
</section>

app/views/feeds/show_font.js.erb
<% typ = params[:type] || 'post' %>
<% collection = @users || @photos %>

<% contents = if params[:type] == 'fav' %>
  <% render '/shared/account_list' %>
<% else %>
  <% render '/shared/photo_list' %>
<% end %>

<% if params[:page] # pagination request %>
  <% if collection.blank? # stop paginating %>
    // set the docHeight greater than actual height
    // and that stops further pagination requests
    docHeight = getDocHeight() + 10000;
  <% else %>
    $('#font_section_container').append('<%= escape_javascript(contents) %>');
    // set the page JS variables
    pageNum = parseInt('<%= params[:page] %>');
    docHeight = getDocHeight();
    doPagination = true;
  <% end %>
  $('.loader').addClass('hidden');
<% else %>
  $('#font_section_container').html('<%= escape_javascript(contents) %>');
  $('.font-detail-cta').removeClass('selected');
  $(".font-detail-cta.<%= typ %>").addClass('selected');
  hideAjaxLoader();
<% end %>

app/views/feeds/unlike_feed.js.erb
// update the likes count
$('#likes_cnt_<%= params[:id] %>').html("<%= pluralize(@photo.likes_count, 'like') %>");
// update the button
var elem = $('#unlike_<%= params[:id] %>');
elem.replaceWith("<%= escape_javascript(render_photo_like_button(@photo)) %>");
hideAjaxLoader();