config/routes.rb
# See how all your routes lay out with "rake routes"
Fontli::Application.routes.draw do
  # Api controller
  match '/api/:action(.:format)', :controller => 'api_actions'

  # new web routes
  match 'feeds' => 'feeds#index', :as => :feeds
  match 'feeds/show/:id' => 'feeds#show', :as => :show_feed
  match 'socialize-feed/:id' => 'feeds#socialize_feed', :as => :socialize_feed
  match 'follow-user/:id' => 'feeds#follow_user', :as => :follow_user
  match 'unfollow-user/:id' => 'feeds#unfollow_user', :as => :unfollow_user
  match 'sos' => 'feeds#sos', :as => :sos
  match 'feed/:id/fonts' => 'feeds#fonts', :as => :feed_fonts
  match 'fonts/:family_id/:font_id' => 'feeds#show_font', :as => :show_font
  match 'recent-fonts' => 'feeds#recent_fonts', :as => :recent_fonts
  match 'profile/:user_id' => 'feeds#profile', :as => :profile
  match 'popular' => 'feeds#popular', :as => :popular
  match 'my-updates' => 'feeds#my_updates', :as => :my_updates
  match 'network-updates' => 'feeds#network_updates', :as => :network_updates
  match 'search-autocomplete' => 'feeds#search_autocomplete', :as => :search_autocomplete
  match 'search' => 'feeds#search', :as => :search
  match "font-autocomplete" => "fonts#font_autocomplete", :as => :font_autocomplete
  match "font-details/:fontname" => "fonts#font_details", :as => :font_details
  match "sub-font-details/:uniqueid" => "fonts#sub_font_details", :as => :sub_font_details
  match 'tag_font' => 'fonts#tag_font', :as => :tag_font

  # Old Unused routes
  match 'post-feed' => 'feeds#post_feed', :as => :post_feed
  match 'publish-feed/:id' => 'feeds#publish_feed', :as => :publish_feed
  match 'detail_view' => 'feeds#detail_view', :as => :detail_view
  match 'get_mentions_list' => 'feeds#get_mentions_list', :as => :get_mentions_list

  # welcome controller
  root :to => 'welcome#index'

  match 'keepalive' => 'welcome#keepalive', :as => :keepalive
  match 'signup/:platform' => 'welcome#signup', :as => :signup
  match 'login/:platform'  => 'welcome#login',  :as => :login
  match 'auth/:platform/callback' => 'welcome#auth_callback', :as => :auth_callback
  match 'logout' => 'welcome#logout', :as => :logout

  # admin controller
  match 'admin' => 'admin#index', :as => :admin
  match 'admin/:action', :controller => 'admin'

  # Resque Web
  mount Resque::Server.new, :at => "/resque"

  # Utils
  constraints :host => /(localhost|staging\.fontli\.com)/i do
    match 'doc' => 'welcome#api_doc'
  end

  # Permalink - Has to be the last one
  match '*url' => 'feeds#permalink'
end

app/models/font.rb
class Font
  include Mongoid::Document
  include Mongoid::Timestamps
  include MongoExtensions

  field :family_unique_id, :type => String
  field :family_id, :type => String
  # Names are reduntant here as its derived from FontDetail
  # We use this only when the details are not available
  field :family_name, :type => String
  field :subfont_name, :type => String
  field :subfont_id, :type => String
  field :agrees_count, :type => Integer, :default => 0
  field :font_tags_count, :type => Integer, :default => 0
  # pick_status is to identify expert/publisher's pick
  field :pick_status, :type => Integer, :default => 0
  field :expert_tagged, :type => Boolean, :default => false

  belongs_to :photo, :index => true, :counter_cache => true
  belongs_to :user, :index => true
  has_many :agrees, :dependent => :destroy
  has_many :font_tags, :autosave => true, :dependent => :destroy
  has_many :fav_fonts, :dependent => :destroy
  has_many :hash_tags, :as => :hashable, :autosave => true, :dependent => :destroy

  validates :family_unique_id, :family_id, :presence => true
  validates :photo_id, :user_id, :presence => true

  attr_accessor :img_url, :thumb_url # BC patch
  after_create :populate_details

  delegate :desc, :owner, :image, :to => :details, :allow_nil => true # also :name, :url

  POPULAR_API_LIMIT = 20
  PICK_STATUS_MAP = { :expert_pick => 1, :publisher_pick => 2, :expert_publisher_pick => 3 }

  class << self
    def [](fnt_id)
      self.where(:_id => fnt_id).first
    end

    def add_agree_for(fnt_id, usr_id, cls_fnt_help = false)
      fnt = self[fnt_id]
      return [nil, :font_not_found] if fnt.nil?
      agr = fnt.agrees.build(:user_id => usr_id)
      saved = agr.my_save(true)
      saved = saved && fnt.photo.update_attribute(:font_help, false) if cls_fnt_help
      saved
    end

    def unagree_for(fnt_id, usr_id)
      fnt = self[fnt_id]
      return [nil, :font_not_found] if fnt.nil?
      agr = fnt.agrees.where(:user_id => usr_id).first
      return [nil, :record_not_found] if agr.nil?
      agr.destroy ? true : [nil, :unable_to_save]
    end

    def tagged_photos_for(opts, lmt = 20)
      page = opts.delete(:page) || 1
      fids = self.where(opts).only(:photo_id).to_a
      return [] if fids.empty?
      offst = (page.to_i - 1) * lmt
      Photo.where(:_id.in => fids.collect(&:photo_id)).desc(:created_at).skip(offst).limit(lmt)
    end

    # Find 3 recently spotted photos for a popular font
    # Uses the cached_popular_foto_ids
    def tagged_photos_popular(famly_id, lmt = 3)
      fids = self.cached_popular_foto_ids_map[famly_id]
      return [] if fids.blank?
      Photo.where(:_id.in => fids).desc(:created_at).limit(lmt)
    end

    # get popular family fonts(grouped) based on total tags_count, for a month
    # total tags_count, includes the count of subfonts as well.
    def cached_popular
      Rails.cache.fetch('popular_fonts', :expires_in => 2.days.seconds.to_i) do
        fnts = self.where(:created_at.gte => 1.months.ago).desc(:created_at).to_a
        resp = fnts.group_by { |f| f[:family_id] }
        resp = resp.sort_by { |fam_id, dup_fts| -dup_fts.sum(&:tags_count) }
        resp.collect { |fam_id, dup_fts| dup_fts.first }
      end
    end

    def popular
      lmt = POPULAR_API_LIMIT
      self.cached_popular.first(lmt)
    end

    # caches a hash of the foto_ids array for every popular font#family_id
    # {'family_id1' => ['foto_id1', 'foto_id2'], 'family_id2' => ['foto_id1'], ..}
    # Note: Since its based on recent_fonts cache, it should have the same expiry as the latter.
    def cached_popular_foto_ids_map
      Rails.cache.fetch('recent_fonts_foto_ids_map', :expires_in => 2.days.seconds.to_i) do
        family_ids = self.api_recent.collect(&:family_id)
        fnts = self.where(:family_id.in => family_ids).only(:family_id, :photo_id).to_a

        ids_map = {}
        fnts.group_by(&:family_id).each do |family_id, fnts_arr|
          ids_map[family_id] = fnts_arr.collect(&:photo_id)
        end
        ids_map
      end
    end

    # reliably find a random photo(selected for header) of all the popular fonts
    # Uses the inefficient skip random count logic, which is the easiest option 
    def random_popular_photo(lmt = 1)
      fids = self.cached_popular_foto_ids_map.values.flatten
      return [] if fids.empty?

      fotos_scope = Photo.where(:_id.in => fids, :show_in_header => true)
      rand_offset = rand(fotos_scope.count - lmt + 1)
      fotos_scope.skip(rand_offset).limit(lmt)
    end

    # fonts with min 3 agrees or a publisher_pick, sorted by updated_at
    def api_recent
      lmt = POPULAR_API_LIMIT
      Rails.cache.fetch('recent_fonts', :expires_in => 2.days.seconds.to_i) do
        fnts = self.where(:agrees_count.gte => 3).to_a
        fnts += self.where(:pick_status.gte => PICK_STATUS_MAP[:publisher_pick]).to_a
        fnts = fnts.sort_by(&:updated_at).reverse
        return [] if fnts.empty?
        resp = fnts.group_by { |f| f[:family_id] }
        resp.collect { |fam_id, dup_fts| dup_fts.first }.first(lmt)
      end
    end

    def search(name,sort = nil,dir = nil)
      return [] if name.blank?
      name = Regexp.escape(name.strip)
      res = self.where(:family_name => /^#{name}.*/i).to_a
      res << self.where(:subfont_name => /^#{name}.*/i).to_a
      res = res.flatten.uniq(&:id)
      res = res.sort{|a,b| a.send(sort) <=> b.send(sort)} if sort
      res = res.reverse if dir == "asc"
      res
    end

    def search_autocomplete(name, lmt=20)
      return [] if name.blank?
      name = Regexp.escape(name.strip)
      res = self.where(:family_name => /^#{name}.*/i).only(:family_name).limit(lmt).collect(&:family_name)
      res + self.where(:subfont_name => /^#{name}.*/i).only(:subfont_name).limit(lmt).collect(&:subfont_name)
    end
  end

  def tagged_photos_count
    @tagged_photos_count ||= Font.where(:family_id => self.family_id).count
  end

  def favs_count
    @favs_count ||= self.fav_fonts.count
  end

  def fav_users(pge, lmt = 20)
    offst = ((pge || 1).to_i - 1) * lmt
    fav_usr_ids = self.fav_fonts.only(:user_id).collect(&:user_id)
    User.where(:_id.in => fav_usr_ids).desc(:points).skip(offst).limit(lmt)
  end

  def hashes=(hshs)
    return true if hshs.blank?
    hshs.each do |h|
      self.hash_tags.build(h)
    end
  end

  def tags_count
    self.font_tags_count
  end

  def heat_map
    tgs = self.font_tags.to_a
    tgs = tgs.group_by { |tg| tg.coords }
    tgs.collect do |coords, tgs_arr|
      x, y = coords.split(',')
      OpenStruct.new(:cx => x, :cy => y, :count => tgs_arr.length)
    end
  end

  def tagged_users
    cols = [:id, :data_filename, :username, :full_name]
    usrs = User.where(:_id.in => self.tagged_user_ids).only(*cols).to_a
    current_user.populate_friendship_state(usrs)
  end

  def tagged_user_ids
    @taggd_usr_ids ||= self.font_tags.only(:user_id).collect(&:user_id)
  end

  def recent_tagged_unames
    usr_ids = self.font_tags.desc(:created_at).limit(2).only(:user_id).collect(&:user_id)
    unames = [] if usr_ids.empty?
    unames ||= User.where(:_id.in => usr_ids).only(:username).collect(&:username)
  end

  # status of current_user with this font - Tagged or Agreed
  # cannot agree on a font, self tagged.
  def my_agree_status
    status = ''
    tagged = self.font_tags.where(:user_id => current_user.id).first
    if tagged.nil?
      agreed = self.agrees.where(:user_id => current_user.id).first
      status = 'Agreed' unless agreed.nil?
    else
      status = 'Tagged'
    end
    status
  end

  # Unique font key. Used to reject duplicate fonts, as
  # a same font can be tagged across multiple photos.
  def key
    "#{self.family_id}_#{self.subfont_id}"
  end

  def my_fav?
    current_user.fav_font_ids.include? self.id
  end

  def img_url
    MyFontsApiClient.font_sample(self.family_id, self.subfont_id)
  end

  def display_name
    self.subfont_id.blank? ? self.family_name : self.subfont_name
  end

  def photo_ids
    [self.photo_id]
  end

  def details
    @details ||= FontDetail.for(self.family_id, self.subfont_id)
  end

  def family_name
    details.try(:name) || self.read_attribute(__method__)
  end

  def subfont_name
    details.try(:name) || self.read_attribute(__method__)
  end

  def myfonts_url
    details.try(:url)
  end

  private

  def populate_details
    fnt_details = MyFontsApiClient.details_for(self.family_id, self.subfont_id)
    FontDetail.ensure_create(fnt_details)
  end
end

app/views/shared/_account.html.erb
<% content_for :custom_js do %>
  photoIds = [];
<% end %>

<% fotos = u.photos.only(:id, :data_filename).limit(4).to_a %>
<div class="limelight-content">
  <a href="<%= profile_path(:user_id => u.id) %>" class="pro-img-big">
    <img src="<%= u.url_large %>" width="100%" height="auto">
    <div class="overlap-d"></div>
  </a>
  <div class="user-detail">
    <a href="<%= profile_path(:user_id => u.id) %>"><%= u.username %></a>
    <a class='profile-name' href="<%= profile_path(:user_id => u.id) %>"><%= u.full_name %></a>
    <%= render_follow_button(u) %>
    <div class="clear"> </div>

    <ul>
      <% fotos.each do |f| %>
        <li rel='popitup' href='<%= show_feed_path(f) %>' data-id='<%= f.id %>'>
          <a href="javascript:;">
            <img src="<%= f.url_thumb %>" width="68" height="68" />
          </a>
        </li>
      <% end %>
    </ul>
    <ul class="subtext">
      <li><a href="<%= profile_path(:user_id => u.id) %>"><%= pluralize(u.photos_count, 'Post') %></a></li>
      <li><a href="<%= profile_path(:user_id => u.id) %>"><%= pluralize(u.my_fonts_count, 'Spotting') %></a></li>
      <li><a href="<%= profile_path(:user_id => u.id) %>"><%= pluralize(u.followers_count, 'Follower') %></a></li>
    </ul>
  </div>
</div>

app/views/shared/_account_list.html.erb
<% half = @users.length / 2 %>
<% half = 1 if @users.length < 2 %>
<div id="limelight-markup" class="wrapper">
  <div class="left-content">
    <% @users.first(half).each do |u| %>
      <%= render '/shared/account', :u => u %>
    <% end %>
  </div>
  <div class="right-content">
    <% @users[half..-1].to_a.each do |u| %>
      <%= render '/shared/account', :u => u %>
    <% end %>
  </div>
</div>

app/views/shared/_android_css_fix.html.erb
<script type='text/javascript'>
  window.onload = function(e) { // Wait for page to finish loading.
    if(navigator != undefined && navigator.userAgent != undefined) {
      user_agent = navigator.userAgent.toLowerCase();
      if(user_agent.indexOf('android') > -1) { // Is Android.
        document.body.setAttribute('class', 'android');
      }
    }
  };
</script>

app/views/shared/_comment_content.html.erb
<% u ||= c.user %>
<% fnts_map ||= [] %>
<div class="comment">
  <a class="propic" href="<%= profile_path(:user_id => u.id) %>">
    <img src="<%= u.url_thumb %>" width="100%" height="auto">
    <div class="overlap"></div>
  </a>
  <ul>
    <li class="a">
      <a href="<%= profile_path(:user_id => u.id) %>"><span class="name"><%= u.username %></span></a>
      <span class="time"><%= timestamp(c.created_at) %></span>
    </li>
    <li class="b">
      <span><%= c.body %></span>
      <% (c.font_tag_ids || []).each do |ft_id| %>
        <% f = fnts_map[ft_id.to_s] %>
        <span>Spotted <%= f.display_name %></span>
      <% end %>
    </li>
  </ul>
</div> <!-- comment -->

app/views/shared/_controls.html.erb
<div class="controls" style="<%= 'top:-130px;' if logged_in? %>">
  <a href="#" class="prev-page">
    <img src="<%= asset_path('left-arrow-big.png') %>" width="50" height="105" alt="left-arrow" title="Previous Page" />
  </a>
  <a href="#" class="next-page">
    <img src="<%= asset_path('right-arrow-big.png') %>" width="50" height="105" alt="right-arrow" title="Next Page" />
  </a>
</div>

app/views/shared/_font_list.html.erb
<% content_for :custom_js do %>
  photoIds = [];
<% end %>

<div class="wrapper recently_spotted">
<% @fonts.each do |f| %>
  <ul>
    <li>
      <a href="<%= show_font_path(f.family_id, :font_id => f.id) %>">
        <img src="<%= f.img_url %>" width="290" height="auto">
        <h5>
          <span><%= f.display_name %></span>
          <% unless f.owner.blank? %>
            <label>by <%= f.owner %></label>
          <% end %>
        </h5>
        <span><%= pluralize(f.tagged_photos_count, 'Photo') %></span>
        <span><%= f.favs_count %> Favourite</span>
      </a>
    </li>
    <% Font.tagged_photos_popular(f.family_id).each do |p| %>
      <li rel='popitup' href='<%= show_feed_path(p) %>' data-id='<%= p.id %>'>
        <a class="spotted-img" href="javascript:;">
          <img src="<%= p.url_thumb %>" width="206" height="206" />
        </a>
      </li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/shared/_header.html.erb
<% if logged_in? %>
  <% notif_cnt = current_user.notifications_count %>
  <div class="tertiary">
    <a href="<%= feeds_path %>" id="logo">Fontli</a>
    <div class="grey-box profile">
      <a href='<%= profile_path %>' class='img-mask'>
        <img width="100%" height="100%" title="profile" src='<%= current_user.url_thumb %>'>
        <div class="overlap"></div>
      </a>
      <div class='notifications-count-box' href='<%= my_updates_path %>'><%= notif_cnt %></div>
    </div>
    <div class="grey-box up"></div>
    <div class="grey-box search">
      <%= form_tag search_path, :method => 'post' do %>
        <input type="text" name="search" placeholder="search" value="<%= params[:search] %>" />
      <% end %>
    </div>
  </div>
<% elsif not_homepage? && params[:controller] == 'feeds' %>
  <div class="tertiary">
    <a href="/" id="logo">Fontli</a>
    <div class="grey-box profile">
      <a href='#' class='img-mask'>
        <div class="overlap"></div>
      </a>
    </div>
    <div class="grey-box up"></div>
    <%= render '/shared/search_box' %>
  </div>
<% else %>
  <div class="primary">
    <a href="/" id="logo">Fontli</a>
    <% if homepage? %><%= render '/shared/search_box' %><% end %>
    <% if false %><a remote="true" data-href="<%= login_path(:default) %>" id="signup">Sign In</a><% end %>
    <span>discover, share, pure type love</span>
  </div>

  <div class="secondary">
    <div class="mobpic">
      <img src="<%= asset_path('phone.png') %>">
      <div id="slideshow" class='phone-top'>
        <div class="active">
          <img src="/perma-assets/images/slides/slide0a.png"/>
        </div>
        <div>
          <img src="/perma-assets/images/slides/slide05.png"/>
        </div>
        <div>
          <img src="/perma-assets/images/slides/slide00.png"/>
        </div>
        <div>
          <img src="/perma-assets/images/slides/slide01.png"/>
        </div>
        <div>
          <img src="/perma-assets/images/slides/slide01b.png"/>
        </div>
        <div>
          <img src="/perma-assets/images/slides/slide02.png"/>
        </div>
        <div>
          <img src="/perma-assets/images/slides/slide02a.png"/>
        </div>
        <div>
          <img src="/perma-assets/images/slides/slide03.png"/>
        </div>
        <div>
          <img src="/perma-assets/images/slides/slide04.png"/>
        </div>
      </div>
    </div>
    <h1 style='color:#999;'>Fontli is a social network for typoholics. Capture typography around you and share it. Let the typetalk develop on Fontli.</h1>
    <% android_href = apple_href = wp_href = 'javascript:;' %>
    <% android_class, apple_class, wp_class = 'android', 'apple', 'wp' %>
    <% if true || mob_req? # take them directly to app download url %>
      <% android_class = apple_class = wp_class = '' %>
      <% android_href = 'https://play.google.com/store/apps/details?id=com.imaginea.fontli' %>
      <% apple_href = 'http://itunes.apple.com/us/app/fontli/id506650372?ls=1&mt=8' %>
      <% wp_href = 'http://www.windowsphone.com/s?appid=0d09f01f-17de-4757-b63c-a1cb32fbd655' %>
    <% end %>
    <div class="qrcode">
      <div class="app-download" style="height:56px;">
        <a href="<%= android_href %>" class='<%= android_class %>' target='blank'>
          <img src="<%= asset_path('Google-Play1.png') %>" width="200" height="56" alt="android-store" title="Play Store" />
        </a>
      </div>
      <div class="app-download">
        <a href="<%= apple_href %>" class='<%= apple_class %>' target='blank'>
          <img src="<%= asset_path('App-Store1.png') %>" width="96" height="30" alt="app-store" title="App Store" />
        </a>
        <a href="<%= wp_href %>" class='<%= wp_class %>' target='blank'>
          <img src="<%= asset_path('Windows-store1.png') %>" width="96" height="30" alt="windows-store" title="Windows Store" />
        </a>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_leaderboard.html.erb
<div id="leader_board" class="list_view">
  <h5>LeaderBoard</h5>
  <ul>
    <li>
      <%= image_tag "profile/profile_1.jpg" %>
      <div>
        <a href="#">San Mario</a><span>Correcting Pixels</span>
      </div>
    </li>
    <li>
      <%= image_tag "profile/profile_1.jpg" %>
      <div>
        <a href="#">Nadia</a><span>Sans Serifian</span>
      </div>
    </li>
    <li>
      <%= image_tag "profile/profile_1.jpg" %>
      <div>
        <a href="#">Diya</a><span>Tahoman</span>
      </div>
    </li>
    <li>
      <%= image_tag "profile/profile_1.jpg" %>
      <div>
        <a href="#">Dorathy</a><span>Correcting Pixels</span>
      </div>
    </li>
    <li>
      <%= image_tag "profile/profile_1.jpg" %>
      <div>
        <a href="#">Shauna</a><span>Caliberi</span>
      </div>
    </li>
    <li>
      <%= image_tag "profile/profile_1.jpg" %>
      <div>
        <a href="#">Surpia Sans</a><span>Correcting Pixels</span>
      </div>
    </li>
  </ul>
</div>

app/views/shared/_most_tagged.html.erb
<div class="list_view">
  <h5>Most Tagged</h5>
  <ul>
    <li>
      <a href="#">Surpia Sans</a>
    </li>
    <li>
      <a href="#">Times new roman</a>
    </li>
    <li>
      <a href="#">Helvitica</a>
    </li>
    <li>
      <a href="#">Franklin Gothic</a>
    </li>
    <li>
      <a href="#">Surpia Sans</a>
    </li>
    <li>
      <a href="#">Times new roman</a>
    </li>
    <li>
      <a href="#">Helvitica</a>
    </li>
  </ul>
</div>

app/views/shared/_navigation.html.erb
<section id="banner" class="small">
<div class="wrap">
  <div id="slider1" class="slider">
    <ul>
      <li class='banner-cta' href='<%= recent_fonts_path %>'>
        <div style="width:305px;background:url('/web-assets/images/pok1.png') no-repeat;">
          <span>Recently Spotted</span>
        </div>
      </li>
      <li class='banner-cta' href='<%= sos_path %>'>
        <div style="width:305px;background:url('/web-assets/images/pok2.png') no-repeat;">
          <span>Type help needed</span>
        </div>
      </li>
      <li class='banner-cta' href='<%= popular_path %>'>
        <div class='img-tile-container'>
          <div class='img-tile' style="background:url('/web-assets/images/pok1.png') no-repeat;">
            <span>Popular</span>
          </div>
          <div class='split'>
            <img width="73" height="74" src="/web-assets/images/twitter-quote.png">
            <img width="73" height="74" src="/web-assets/images/twitter-quote.png">
            <div></div>
          </div>
          <div class='split'>
            <img width="73" height="74" src="/web-assets/images/twitter-quote.png">
            <img width="73" height="74" src="/web-assets/images/twitter-quote.png">
            <div></div>
          </div>
        </div>
      </li>
      <li class='banner-cta' href='<%= network_updates_path %>'>
        <div style="width:305px;background:url('/web-assets/images/pok1.png') no-repeat;">
          <span>Network Updates</span>
        </div>
      </li>
      <li class='banner-cta' href='<%= feeds_path %>'>
        <div style="width:305px;background:url('/web-assets/images/pok2.png') no-repeat;">
          <span>Feeds</span>
        </div>
      </li>
    </ul>
  </div>
  <%= render 'shared/controls' %>
</div>
</section>

app/views/shared/_photo_list.html.erb
<% content_for :custom_js do %>
  photoIds = <%= @photos.collect(&:id).to_json.html_safe %>;
<% end %>

<% usr = @photos.first.try(:user) if @users_map.nil? # for user profile %>
<% section ||= '' %>
<% @photos.each do |f| %>
  <div rel='popitup' href='<%= show_feed_path(f) %>' data-id=<%= f.id %> class='feed-item'>
    <section>
      <%= render 'shared/photo_list_section', :f => f, :section => section %>
    </section>
    <% u = usr || @users_map[f.user_id].first %>
    <footer class='<%= section %>'>
      <%= render 'shared/photo_list_footer', :u => u, :f => f, :section => section %>
    </footer>
  </div>
<% end %>

app/views/shared/_photo_list_footer.html.erb
<% unless section == 'profile-post' %>
  <a href="<%= profile_path(:user_id => u.id) %>" class="profile-img">
    <img width="100%" height="100%" alt="profile-image" src="<%= u.url_thumb %>" />
    <div class="overlap"></div>
  </a>
<% end %>
<ul>
  <% unless section == 'profile-post' %>
    <li class="profile-name">
      <a href="<%= profile_path(:user_id => u.id) %>"><%= u.username %></a>
    </li>
  <% end %>
  <li class="profile-detail popitup">
    <%= photo_details_li(f) %>
  </li>
  <% unless f.address.blank? %>
    <li class="profile-location">
      <span><%= f.address %></span>
    </li>
  <% end %>
</ul>

app/views/shared/_search_box.html.erb
<div class="grey-box search">
  <%= form_tag search_path, :method => 'post' do %>
    <input type="text" name="search" placeholder="search" value="<%= params[:search] %>" />
  <% end %>
</div>