config/routes.rb
# See how all your routes lay out with "rake routes"
Fontli::Application.routes.draw do
  # Api controller
  match '/api/:action(.:format)', :controller => 'api_actions'

  # new web routes
  match 'feeds' => 'feeds#index', :as => :feeds
  match 'feeds/show/:id' => 'feeds#show', :as => :show_feed
  match 'socialize-feed/:id' => 'feeds#socialize_feed', :as => :socialize_feed
  match 'follow-user/:id' => 'feeds#follow_user', :as => :follow_user
  match 'unfollow-user/:id' => 'feeds#unfollow_user', :as => :unfollow_user
  match 'sos' => 'feeds#sos', :as => :sos
  match 'feed/:id/fonts' => 'feeds#fonts', :as => :feed_fonts
  match 'fonts/:family_id/:font_id' => 'feeds#show_font', :as => :show_font
  match 'recent-fonts' => 'feeds#recent_fonts', :as => :recent_fonts
  match 'profile/:user_id' => 'feeds#profile', :as => :profile
  match 'popular' => 'feeds#popular', :as => :popular
  match 'my-updates' => 'feeds#my_updates', :as => :my_updates
  match 'network-updates' => 'feeds#network_updates', :as => :network_updates
  match 'search-autocomplete' => 'feeds#search_autocomplete', :as => :search_autocomplete
  match 'search' => 'feeds#search', :as => :search
  match "font-autocomplete" => "fonts#font_autocomplete", :as => :font_autocomplete
  match "font-details/:fontname" => "fonts#font_details", :as => :font_details
  match "sub-font-details/:uniqueid" => "fonts#sub_font_details", :as => :sub_font_details
  match 'tag_font' => 'fonts#tag_font', :as => :tag_font

  # Old Unused routes
  match 'post-feed' => 'feeds#post_feed', :as => :post_feed
  match 'publish-feed/:id' => 'feeds#publish_feed', :as => :publish_feed
  match 'detail_view' => 'feeds#detail_view', :as => :detail_view
  match 'get_mentions_list' => 'feeds#get_mentions_list', :as => :get_mentions_list

  # welcome controller
  root :to => 'welcome#index'

  match 'keepalive' => 'welcome#keepalive', :as => :keepalive
  match 'signup/:platform' => 'welcome#signup', :as => :signup
  match 'login/:platform'  => 'welcome#login',  :as => :login
  match 'auth/:platform/callback' => 'welcome#auth_callback', :as => :auth_callback
  match 'logout' => 'welcome#logout', :as => :logout

  # admin controller
  match 'admin' => 'admin#index', :as => :admin
  match 'admin/:action', :controller => 'admin'

  # Resque Web
  mount Resque::Server.new, :at => "/resque"

  # Utils
  constraints :host => /(localhost|staging\.fontli\.com)/i do
    match 'doc' => 'welcome#api_doc'
  end

  # Permalink - Has to be the last one
  match '*url' => 'feeds#permalink'
end

app/controllers/welcome_controller.rb
require 'auth_client'
require 'storify_client'

class WelcomeController < ApplicationController
  include AuthClient
  skip_before_filter :login_required, :except => [:logout]
  skip_before_filter :set_current_controller, :only => [:keepalive]

  layout :select_layout

  def keepalive
    render :text => 'Success'
  end

  def index
    redirect_to(feeds_url) && return if logged_in?
    @story   = StorifyStory.random_story
    @popular = Photo.for_homepage.only(:id,:data_filename).to_a
    @homepage, @meta_title = true, 'Home'
  end

  def login
    return if request.get?
    self.send(params[:platform] + "_login")
  end

  def signup
    @user = User.new params[:user]
    return if request.get?
    if @user.save
      @user.send :send_welcome_mail!
      session[:user_id] = @user.id.to_s # login
      redirect_to feeds_url
    end
  end

  def auth_callback
    self.send(params[:platform] + "_callback")
  end

  def logout
    session[:user_id] = nil
    redirect_to test_url
  end

  def api_doc
    render 'api_doc', :layout => false
  end

private

  def facebook_login
    if fb_authorized?
      usr_obj = FbGraph::User.me(fb_client.access_token)
      check_and_handle_fb_user(usr_obj)
    else
      auth_url = fb_authorize
      redirect_to auth_url
    end
  end

  def twitter_login
    if twt_authorized?
      usr_hsh = twt_client.info
      check_and_handle_twt_user(usr_hsh)
    else
      resp = twt_get_token
      session[:twt_request_token] = resp.token
      session[:twt_request_token_secret] = resp.secret
      redirect_to resp.authorize_url
    end
  end

  def default_login
    uname, pass = [params[:username], params[:password]]
    if uname.blank? || pass.blank?
      flash.now[:alert] = 'Username or Password is blank!'
      return false
    end
    u = User.login uname, pass
    unless u.nil?
      session[:user_id] = u.id
      redirect_to feeds_url
    else
      flash.now[:alert] = 'Invalid username or password!'
    end
  end

  def twitter_callback
    if params[:denied]
      redirect_to login_url(:default), :alert => 'Unauthorized!'
      return
    end

    # Exchange the request token for an access token.
    resp = twt_authorize params[:oauth_verifier]

    if twt_authorized?
      # Storing the access tokens so we don't have to go back to Twitter again
      # in this session.  We can also consider persisting these details in DB.
      session[:twt_access_token] = resp.token
      session[:twt_secret_token] = resp.secret
      usr_hsh = JSON.parse resp.response.body
      check_and_handle_twt_user(usr_hsh)
    else
      redirect_to login_url(:default), :alert => 'Twitter Auth failed!'
    end
  end

  def facebook_callback
    if params[:error] == "access_denied"
      redirect_to login_url(:default), :alert => 'Unauthorized!'
      return
    end

    token = fb_get_token(params[:code])

    if token
      session[:fb_access_token] = token.token
      usr_obj = FbGraph::User.me(token)
      check_and_handle_fb_user(usr_obj)
    else
      redirect_to login_url(:default), :alert => 'Facebook Auth failed!'
    end
  end

  def check_and_handle_twt_user(usr_hsh)
    usr = User.by_extid(usr_hsh['id_str'])
    if usr.nil? # new user
      @user = User.new(
        :username => usr_hsh['screen_name'],
        :email => usr_hsh['email'],
        :full_name => usr_hsh['name'],
        :extuid => usr_hsh['id_str'],
        :description => usr_hsh['description'],
        :website => usr_hsh['url']
      )
      @avatar_url = usr_hsh['profile_image_url']
      render :signup, :layout => 'old'
    else
      session[:user_id] = usr.id
      redirect_to feeds_url
    end
  end

  def check_and_handle_fb_user(usr_obj)
    usr = User.by_extid(usr_obj.id)
    if usr.nil? # new user
      @user = User.new(
        :username => usr_obj.identifier,
        :email => usr_obj.email,
        :full_name => usr_obj.name,
        :extuid => usr_obj.id,
        :description => usr_obj.description,
        :website => usr_obj.link
      )
      @avatar_url = usr_obj.picture
      render :signup, :layout => 'old'
    else
      session[:user_id] = usr.id
      redirect_to feeds_url
    end
  end

  def select_layout
    case params[:action].to_sym
    when :login
      'plain'
    when :signup
      'old'
    else
      'application'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_signin.html.erb
<div class="signin" >
  <div class="innershade">
    <a class="img-cross">
      <img src="<%= asset_path('cross-signin.png') %>" width="22" height="22" alt="" title="" />
    </a>
    <div class="image-container">
      <img src="<%= asset_path('fontli-logo.png') %>" width="150" height="85" alt="" title="" />
      <h2 class="signin">Sign in</h2>
    </div>

    <div class="signin-panel">
      <div class="credential-panel">
      <%= form_tag login_path(:default) do %>
        <input type="text" name="username" placeholder="Username or Email Id" class="credential" />
        <input type="password" name="password" placeholder="Password" class="credential" />
        <a>Forgot Password?</a>
        <button>Sign in</button>
      <% end %>
      </div>

      <div class="networking" >
        <div class="membership">
          <span>Not a member?</span>
          <p>Sign up now with</p>
        </div>
        <a href='<%= login_path(:facebook) %>' class="social">
          <img src="<%= asset_path('facebook-white.png') %>" width="12" height="25" alt="" title="" />
          <span>Connect with Facebook</span>
        </a>
        <a href='<%= login_path(:twitter) %>' class="social">
          <img src="<%= asset_path('twitter-white.png') %>" width="24" height="22" alt="" title="" class="twitter" />
          <span>Connect with Twitter</span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/welcome/api_doc.html.erb
<% require 'api_helper' %>

<!DOCTYPE html>
<html>
  <head>
    <title>Fontli: API Doc</title>
    <style type="text/css">
      p { margin:10px 0; padding:0; }
      .note { font-weight: bold; color: gray; }
      #methods { padding: 10px; border-top: 1px solid black; }
      #methods .name { font-weight: bold; }
      #methods .collection { color: gray; margin-left: 20px; }
      #methods .returns { padding-bottom: 10px; border-bottom: 1px dotted gray; }
    </style>
  </head>

  <body>
    <h3>API Documentation</h3>
    <p>All API methods(except <code>signin, signup, login check</code>) requires <code>auth_token</code> param to identify the user session. User-session(and hence the <code>auth_token</code>) expires in 4weeks by default and user has to be signed in again upon expiry.</p>
    <p><span class="note">Note:</span> For FB/Twitter users, there's no concept of sessions. The state is controlled using encrypted <code>extuid_token</code> - derived from <code>auth_token</code>.</p>
    <p>All API response will include: </p>
    <pre>
      1. response: Actual response of the action as defined below, specific to action, can be empty.
      2. status:   Will be "Success" on success and "Failure" on failure.
      3. errors:   Comma seperated string of errors, if status is "Failure", can be empty on "Success".
    </pre>

    <div id="methods">
      <% ApiHelper::SIGNATURE_MAP.each do |k, v| %>
        <p class='name'>/api/<%= k.to_s %></p>
        <p class='accepts'>Accepts: <%= ApiHelper.accepts_label_for(k) %></p>
        <div class='collection'>
          <%= ApiHelper.collection_label_for(k) %>
        </div>
        <p class='returns'>Returns: <%= ApiHelper.returns_label_for(k) %></p>
      <% end %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<% content_for :pre_content do %>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <div id='qr_pop'>
    <%= render 'shared/qr_popup' %>
  </div>
<% end %>
<% content_for :custom_js do %>
  photoIds = <%= @popular.collect(&:id).to_json.html_safe %>;
<% end %>

<section id="secondaryHeader">
<div class="wrapper">
  <blockquote>
    <!--<a class="avatar"><img src="<%= @story.avatar %>" width="73" height="71" /></a>-->
    <p>
      <%= @story.text %> <br />
      <cite><%= @story.name %></cite>
      <a class='storify-link' href="http://storify.com" target='blank'>Powered by Storify</a>
    </p>
  </blockquote>
  <aside>
  <% if false %>
    <button id="join_fontli" href="<%= signup_path(:default) %>">
      <span>Join <%= number_with_delimiter(User.count) %></span>
      <span>typoholics</span>
    </button>
  <% elsif true %>
    <button id="join_fontli" href="<%= popular_path(:type => 'post') %>">
      <span class='join-cta'>
        Discover
        <span><%= number_with_delimiter(User.count) %></span>
        typoholics
      </span>
    </button>
  <% else %>
    <button style='cursor:default;'>
      <% if false # countdown not required for now %>
      <span data-count='<%= user_countdown_count %>' class='user-countdown'>
        <% user_countdown_count.to_s.length.times do |i| %>
          <strong class='<%= i %>'><%= 0 %></strong>
        <% end %>
        typoholics
      </span>
      <% end %>
      <span><%= number_with_delimiter(User.count) %></span>
      <span>typoholics</span>
    </button>
  <% end %>
    <div class="share">
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.fontli.com" data-text="@fontli, Fontli- discover and share pure type love!"></a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      <div class="fb-like" data-href="http://www.fontli.com/" data-send="false" data-layout="button_count" data-show-faces="false"></div>
    </div>
  </aside>
</div>
</section>

<section id="banner" class="big">
<div class="wrap slide-banner">
  <div id="slider1" class="slider">
    <ul>
      <% @popular.each_with_index do |p, i| %>
      <li data-id='<%= p.id %>' href='<%= show_feed_path(p) %>' rel='popitup'>
        <div style='background: none no-repeat; width:305px;height:305px;'>
          <div class="img-shadow"></div>
          <% if(i < 9) # load only the first 10 images upfront %>
            <img src="<%= p.url(:medium) %>" style="width:305px;height:305px;" />
          <% else # rest are loaded later %>
            <img src="<%= render('/shared/black_img_data') %>" xsrc="<%= p.url(:medium) %>" style="width:305px;height:305px;" />
          <% end %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <%= render 'shared/controls' %>
</div>
</section>

<!-- preload images for popup -->
<% @popular.each do |p| %>
  <img xsrc="<%= p.url(:large) %>" class='hidden-img' style="display:none;" />
<% end %>

app/views/welcome/index_old.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fontli</title>
    <meta content="charset=utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0,maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="target-densitydpi=device-dpi">
    <meta name="apple-mobile-web-app-status-bar-style" content="translucent-black" />
    <meta name="description" content="Fontli lets designers and type-enthusiasts discover new fonts and great Typography. Using Fontli, you can capture interesting Typography from everyday life and share it with a vibrant community of type lovers." />

    <link rel="image_src" type="image/gif" href="http://www.fontli.com/splash-assets/images/fontli-thumbnail-new.gif" />
    <link rel="apple-touch-icon" href="/perma-assets/images/icon.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="/perma-assets/images/ipad.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="/perma-assets/images/Icon4.png" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
      function slideSwitch() {
        var $active = $('#slideshow DIV.active');
        if ( $active.length == 0 ) $active = $('#slideshow DIV:last');
        // use this to pull the divs in the order they appear in the markup
        var $next =  $active.next().length ? $active.next() : $('#slideshow DIV:first');
        // uncomment below to pull the divs randomly
        // var $sibs  = $active.siblings();
        // var rndNum = Math.floor(Math.random() * $sibs.length );
        // var $next  = $( $sibs[ rndNum ] );
        $active.addClass('last-active');
        $next.css({opacity: 0.0})
          .addClass('active')
          .animate({opacity: 1.0}, 1000, function() {
            $active.removeClass('active last-active');
          });
      }

      $(function() {
        setInterval( "slideSwitch()", 5000 );
      });
    </script>
    <link rel="stylesheet"  href="/perma-assets/css/app.css"  media="screen" />
    <!--[if IE]><link rel="stylesheet" type="text/css"  href="/perma-assets/css/ie.css"/><![endif]-->
    <style type="text/css">
      div.share { margin-top:20px; margin-bottom: 10px; }
      .twitter-share-button { display: block; margin-bottom: 10px; }
    </style>
  </head>
  <body>
    <% is_mob_req = mob_req? %>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=262992783766760";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div id="homepage">
      <div class="clear">
        <div id="<%= is_mob_req ? 'iphone' : 'sidebar' %>">
          <div id="fontli">
            <h1 class="logo"><a href="http://www.fontli.com">Fontli</a></h1>
            <div id="hello_fontli">
              <h1>Pure Type Love!</h1>
              <p>Embrace the beautiful world of Typography. Capture, Share and Discover. See your favourite Typefaces in action. Meet crazy typoholics.
              </p>

              <h1<% unless is_mob_req %> id="trademark"<% end %> ><a target="blank" href="http://itunes.apple.com/us/app/fontli/id506650372?ls=1&mt=8"><img src="/perma-assets/images/<%= 'iphone_' if is_mob_req %>icon.png"/></a><a target="blank" href="http://itunes.apple.com/us/app/fontli/id506650372?ls=1&mt=8"><img src="/perma-assets/images/appstore.png" alt="appstore" title="Fontli - available in Appstore" style="width:110px;"></a><a target="blank" href="http://www.windowsphone.com/s?appid=0d09f01f-17de-4757-b63c-a1cb32fbd655"><img src="/perma-assets/images/windowsstore.png" alt="marketplace" title="Fontli - available in marketplace" style="width:110px;"></a></h1>
            </div>
            <div class="share">
              <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.fontli.com" data-text="@fontli, Fontli- discover and share pure type love!"></a>
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
              <div class="fb-like" data-href="http://www.fontli.com" data-send="false" data-layout="button_count" data-show-faces="false"></div>
            </div>

          </div>
        </div>

        <div id="content" class="resizetoweb" >
          <div id="slidebody">
            <% unless is_mob_req %>
            <div class="freetag">"its free"</div>
            <div id="slideshow">
              <div class="active">
                <img src="/perma-assets/images/slides/slide0a.png"/>
              </div>
              <div>
                <img src="/perma-assets/images/slides/slide05.png"/>
              </div>
              <div>
                <img src="/perma-assets/images/slides/slide00.png"/>
              </div>
              <div>
                <img src="/perma-assets/images/slides/slide01.png"/>
              </div>
              <div>
                <img src="/perma-assets/images/slides/slide01b.png"/>
              </div>
              <div>
                <img src="/perma-assets/images/slides/slide02.png"/>
              </div>
              <div>
                <img src="/perma-assets/images/slides/slide02a.png"/>
              </div>
              <div>
                <img src="/perma-assets/images/slides/slide03.png"/>
              </div>
              <div>
                <img src="/perma-assets/images/slides/slide04.png"/>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>

      <div id="copyright">
        <p><a target="_blank" href="http://fontli.tumblr.com">Blog</a>&nbsp;|&nbsp;<a target="_blank" href="http://twitter.com/fontli">@fontli</a>&nbsp;|&nbsp;<a href="/faq-web.html">FAQ</a>&nbsp;|&nbsp;<a href="/terms-web.html">Terms</a>&nbsp;|&nbsp;<a href="/privacy-web.html">Privacy</a>&nbsp;|&nbsp;Mail your feedback and enquiries to <a href="mailto:info@fontli.com">info@fontli.com</a></p>
        <p>Fontli is freshly cooked at <a target="blank" href="http://www.imaginea.com/labs">Imaginea Labs</a>. Copyright &copy; <%= Time.now.year %>, Pramati Technologies Private Limited.</p>
      </div>
    </div>

  </body>
</html>

app/views/welcome/login.html.erb
<div class="signin" >
  <div class="innershade">
    <a class="img-cross">
      <img src="<%= asset_path('cross-signin.png') %>" width="22" height="22" alt="" title="" />
    </a>
    <div class="image-container">
      <img src="<%= asset_path('fontli-logo.png') %>" width="150" height="85" alt="" title="" />
      <h2 class="signin">Sign in</h2>
    </div>

    <div class="signin-panel">
      <div class="credential-panel">
      <%= form_tag login_path(:default) do %>
        <input type="text" name="username" placeholder="Username or Email Id" class="credential" />
        <input type="password" name="password" placeholder="Password" class="credential" />
        <a>Forgot Password?</a>
        <button>Sign in</button>
      <% end %>
      </div>

      <div class="networking" >
        <div class="membership">
          <span>Not a member?</span>
          <p>Sign up now with</p>
        </div>
        <a href='<%= login_path(:facebook) %>' class="social">
          <img src="<%= asset_path('facebook-white.png') %>" width="12" height="25" alt="" title="" />
          <span>Connect with Facebook</span>
        </a>
        <a href='<%= login_path(:twitter) %>' class="social">
          <img src="<%= asset_path('twitter-white.png') %>" width="24" height="22" alt="" title="" class="twitter" />
          <span>Connect with Twitter</span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/welcome/login.js.erb
hideAjaxLoader();
$('#popup_container').html('<%= escape_javascript(render('welcome/signin')) %>');
$('#popup_container').show();

app/views/welcome/signup.html.erb
<%= signup_welcome_note %>

<h3>Register</h3>

<%= errors_for @user %>

<%= form_for @user, :url => signup_path(params[:platform] || :default), :html => {:id => 'signup_form'} do |f| %>

  <%= hidden_user_detail_tags(f) %>

  <label>Username</label>
  <%= f.text_field :username, :required => true %>

  <label>Full Name</label>
  <%= f.text_field :full_name %>

  <label>Email</label>
  <%= f.email_field :email, :required => true %>

  <label>Password</label>
  <%= f.password_field :password, :required => true %>

  <label>Confirm Password</label>
  <%= f.password_field :password_confirmation %>

  <% if params[:platform] == 'default' %>
    <label>Avatar</label>
    <%= f.file_field :avatar, :accept => 'image/*' %>
  <% end %>

  <label>Description</label>
  <%= f.text_area :description, :placeholder => 'Optional (120 chars max.)' %>

  <label>Website</label>
  <%= f.url_field :website, :placeholder => 'Optional' %>

  <div class='submit'>
    <button type="submit" value="signin">Register</button>
    <div class='cta'>
      <%= link_to 'Cancel', test_path %>
    </div>
    <div class='clear'></div>
  </div>
<% end %>
<div class='clear'></div>